world: dota
joinDifference: 1
maxTimeEmpty: 300
clans:
 red: 
  baseRegion: redBase
  spawn: 
   x: -1189
   y: 48
   z: 444
 blue:
  baseRegion: blueBase
  spawn:
   x: -943
   y: 48
   z: 187