name: SimpleClansExtensions
main: com.barroncraft.sce.SimpleClansExtensions
version: 3.7
depend: [SimpleClans, WorldGuard]
commands:
  sce:
    description: Various extra commands added to Simple Clans
    usage: /sce join [red|blue]
    permission-message: You don't have permission to use this command.
